# ============================
# Deployment: Nest 应用
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-learn-nest
spec:
  replicas: 1 # 高可用，启动 2 个 Pod
  selector:
    matchLabels:
      app: start-learn-nest
  template:
    metadata:
      labels:
        app: start-learn-nest
    spec:
      containers:
        - name: start-learn-nest
          image: start-learn-nest:v11.0
          imagePullPolicy: Never # 使用本地镜像
          ports:
            - containerPort: 3100
          envFrom:
            - configMapRef:
                name: start-learn-nest-config
            - secretRef:
                name: start-learn-nest-secret
          readinessProbe:
            httpGet:
              path: /
              port: 3100
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'

---
# ============================
# Service: 对外访问
# ============================
apiVersion: v1
kind: Service
metadata:
  name: start-learn-nest-service
spec:
  type: NodePort
  selector:
    app: start-learn-nest
  ports:
    - port: 3100 # Service 内部端口
      targetPort: 3100 # Pod 容器端口
      nodePort: 30081 # 宿主机访问端口
